---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[site-svntypo3org::default]
    attributes:
      dev_mode: true
      site-svntypo3org:
        hostname: svn.vagrant
        ssl_certificate: wildcard.vagrant
        forge_role: site-forge
    driver_config:
      network:
      - ["private_network", {ip: "192.168.88.84"}]
